package kirillgontov.cloudstorage.common;

public enum Command {
    REGISTER, LOGIN,
    REGISTER_SUCCESS, EMAIL_EXISTS, USERNAME_EXISTS, USERNAME_EMPTY, PASSWORD_INCORRECT, LOGIN_SUCCESS,
    UPLOAD, DOWNLOAD, DELETE,
    UPLOAD_FAILED, UPLOAD_SUCCESS, DELETE_FAILED, DELETE_SUCCESS, DOWNLOAD_FAILED, DOWNLOAD_SUCCESS;

}
